# Generated by Django 5.1.7 on 2025-03-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_descriptiion',
            new_name='product_description',
        ),
    ]
