# Generated by Django 5.1.7 on 2025-03-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0006_alter_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(max_length=200),
        ),
    ]
